name: Deploy to Server
on: [push]
jobs:
  AWS-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo $\{\{ secrets.SSH_KEY \}\} | base64 -d > key.pem
      - run: chmod 400 key.pem
      - run: ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@[your server ip/domain name] 'cd ~/[your git folder]; git pull; docker-compose down; docker-compose up -d --build'